CREATE TABLE companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    sharepoint_root_folder text,
    company_folder text NOT NULL,
    po_matching_folder text NOT NULL,
    aliases text NOT NULL DEFAULT '',
    vat_number text,
    address text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    aliases text NOT NULL DEFAULT '',
    default_company_id bigint REFERENCES companies(id),
    default_company text,
    contact_email text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE,
    entra_object_id uuid UNIQUE,
    email text UNIQUE,
    display_name text NOT NULL,
    role text NOT NULL,
    password_hash text,
    password_salt text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (username IS NOT NULL OR entra_object_id IS NOT NULL)
);

CREATE TABLE company_user_access (
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_level text NOT NULL DEFAULT 'member',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (company_id, user_id)
);

CREATE TABLE user_sessions (
    token_hash text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

CREATE TABLE approval_matrix (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint REFERENCES companies(id) ON DELETE CASCADE,
    company text NOT NULL,
    supplier_id bigint REFERENCES suppliers(id) ON DELETE CASCADE,
    supplier text NOT NULL,
    approver1_name text NOT NULL,
    approver1_email text NOT NULL,
    approver2_name text,
    approver2_email text,
    effective_from date,
    effective_to date,
    UNIQUE (company, supplier)
);

CREATE TABLE supplier_terms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint REFERENCES companies(id) ON DELETE CASCADE,
    company text NOT NULL,
    supplier_id bigint REFERENCES suppliers(id) ON DELETE CASCADE,
    supplier text NOT NULL,
    supplier_account_number text,
    default_payment_method text,
    payment_terms_notice text,
    bank_account text,
    UNIQUE (company, supplier_account_number)
);

CREATE UNIQUE INDEX idx_supplier_terms_without_account
    ON supplier_terms (company, supplier)
    WHERE supplier_account_number IS NULL;

CREATE TABLE process_configuration (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_by bigint REFERENCES users(id),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE irj_sequence (
    id smallint PRIMARY KEY CHECK (id = 1),
    next_number bigint NOT NULL DEFAULT 1 CHECK (next_number > 0)
);

CREATE TABLE invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id text NOT NULL,
    attachment_id text NOT NULL,
    internet_message_id text,
    sender_name text,
    sender_address text,
    subject text,
    received_at text,
    original_filename text NOT NULL,
    stored_path text NOT NULL,
    size_bytes bigint,
    status text NOT NULL,
    created_at text NOT NULL,
    sharepoint_item_id text,
    sharepoint_web_url text,
    irj_number text UNIQUE,
    company_id bigint REFERENCES companies(id),
    company text,
    supplier_id bigint REFERENCES suppliers(id),
    supplier text,
    supplier_invoice_number text,
    po_number text,
    invoice_type text,
    invoice_date text,
    invoice_value double precision,
    currency text,
    ai_confidence double precision,
    ai_field_confidences text,
    ai_review_warnings text,
    approver1_name text,
    approver1_email text,
    approver1_decision text,
    approver1_date text,
    approver1_comments text,
    approver2_name text,
    approver2_email text,
    approver2_decision text,
    approver2_date text,
    approver2_comments text,
    po_query_notes text,
    po_query_category text,
    po_query_contact text,
    payment_date text,
    supplier_account_number text,
    payment_reference text,
    payment_method text,
    paid_by text,
    reconciliation_date text,
    reconciliation_notes text,
    reconciled_by text,
    rejection_reason text,
    review_reason text,
    review_return_status text,
    duplicate_of_invoice_id bigint REFERENCES invoices(id),
    hold_reason text,
    hold_level integer,
    sage_registered_at text,
    sage_reference text,
    sage_registered_by text,
    is_foreign_payment integer,
    payment_route_decided_at text,
    payment_route_decided_by text,
    foreign_allocation_date text,
    foreign_allocation_reference text,
    foreign_allocated_by text,
    cancelled_at text,
    cancelled_by text,
    cancellation_reason text,
    UNIQUE (message_id, attachment_id)
);

CREATE INDEX idx_invoices_created_at ON invoices (created_at DESC);
CREATE INDEX idx_invoices_status_created_at ON invoices (status, created_at DESC);
CREATE INDEX idx_invoices_company_id ON invoices (company_id);
CREATE INDEX idx_invoices_supplier_id ON invoices (supplier_id);
CREATE INDEX idx_invoices_company_supplier_number
    ON invoices (company_id, supplier_id, lower(supplier_invoice_number))
    WHERE company_id IS NOT NULL
      AND supplier_id IS NOT NULL
      AND supplier_invoice_number IS NOT NULL
      AND cancelled_at IS NULL;

CREATE TABLE activity_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    target_role text NOT NULL,
    message text NOT NULL,
    invoice_id bigint REFERENCES invoices(id) ON DELETE SET NULL,
    company_id bigint REFERENCES companies(id),
    actor_user_id bigint REFERENCES users(id),
    event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_activity_events_id ON activity_events (id);
CREATE INDEX idx_activity_events_invoice ON activity_events (invoice_id, created_at DESC);
CREATE INDEX idx_activity_events_company ON activity_events (company_id, created_at DESC);

-- company_user_access is staged for PostgreSQL Row-Level Security once Entra
-- web sign-in is implemented and each transaction can set a trusted user ID.
-- Enabling RLS before that identity context exists would hide company-owned
-- rows from the application rather than protecting them correctly.
