CREATE TABLE auth_sessions (
    token_hash text PRIMARY KEY,
    username text NOT NULL,
    display_name text NOT NULL,
    email text,
    role text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

CREATE INDEX idx_auth_sessions_expires_at ON auth_sessions (expires_at);

CREATE TABLE oauth_flows (
    state text PRIMARY KEY,
    flow_json jsonb NOT NULL,
    expires_at timestamptz NOT NULL
);

CREATE INDEX idx_oauth_flows_expires_at ON oauth_flows (expires_at);

CREATE TABLE outlook_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id text NOT NULL,
    message_id text NOT NULL,
    resource text NOT NULL,
    change_type text NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    last_error text,
    payload jsonb NOT NULL,
    UNIQUE (subscription_id, resource, change_type)
);

CREATE INDEX idx_outlook_notifications_status_received
    ON outlook_notifications (status, received_at);
